dotnet pack ./DWIS.API.DTO/DWIS.API.DTO.csproj --output reference-implementation-packages -p:PackageVersion=2.2.9 --version-suffix "dev"
dotnet pack ./DWIS.OPCUA.Schemas/DWIS.OPCUA.Schemas.csproj --output reference-implementation-packages -p:PackageVersion=2.2.9  --version-suffix "dev"
dotnet pack ./DWIS.OPCUA.Vocabulary/DWIS.OPCUA.Vocabulary.csproj --output reference-implementation-packages -p:PackageVersion=2.2.9  --version-suffix "dev"
dotnet pack ./DWIS.Vocabulary.ResourceIntegration/DWIS.Vocabulary.ResourceIntegration.csproj --output reference-implementation-packages -p:PackageVersion=2.2.9  --version-suffix "dev"
dotnet pack ./DWIS.SPARQL.Utils/DWIS.SPARQL.Utils.csproj --output reference-implementation-packages -p:PackageVersion=2.2.9  --version-suffix "dev"
dotnet pack ./DWIS.OPCUA.Configuration/DWIS.OPCUA.Configuration.csproj --output reference-implementation-packages -p:PackageVersion=2.2.9  --version-suffix "dev"