name: Generate cleaned vocabulary and packages
on: 
  workflow_dispatch:
  push: # push must be changed to trigger after md's have been generated (workflow trigger?)
    paths:
      - 'docs/vocabulary_development/definitions/**.md' 

jobs:
  generate_vocabulary:
    runs-on: ubuntu-latest
    env:
      PACKAGE_OUTPUT_FOLDER: "${{ github.workspace }}/src/reference-implementation-packages"
      NUGET_SECRET_API: ${{ secrets.NUGET_SECRET_API }}

    
    steps:
      - uses: actions/checkout@v2   

      - name: Build and pack
        run: |
          cd "${{ github.workspace }}/src"
          dotnet pack DWIS.Blackboard.Base.sln --output $Env:PACKAGE_OUTPUT_FOLDER -p:PackageVersion=1.0."${{ github.run_number }}"

      - name: 'Push to NuGet.org'
        run: |
          cd $Env:PACKAGE_OUTPUT_FOLDER
          dotnet nuget push "*.nupkg" -k "$env:NUGET_SECRET_API" -s https://api.nuget.org/v3/index.json --skip-duplicate
